### ISSUE TITLE
on mobile (android chrome) can not finish creation of account

### ISSUE THREAD

**Issue by lospringliu** [DeFUCC/gun-vue#12]
after entering the encrypt passphrase, it does not show the links to download json files or qrcode 

and the modal can not be closed

**Comment by davay42** [comment]
Oh, that's another blind spot. I've never debugged android browsers. I'll be thankful if you can find the source of the problem.

**Comment by lospringliu** [comment]
some screenshots. It looks like the browser in mobile behaves differently
- in space, does not interact
- in user icon, after new key and encrypted, no way to break, and nowhere to save keys / QRs, the modal can not be closed either
- gun connection seems very lazy in mobile
- if logoff but do not close the tab, then create new account, authenticate as the existing one

<img width="402" alt="image" src="https://user-images.githubusercontent.com/9952753/156813559-9364e644-ccd7-4915-b15b-9c78df2a1678.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/9952753/156813845-9a0830f8-d6aa-4d66-8684-2d533d5628d1.png">

**Comment by lospringliu** [comment]
the version on box is 91, let me check if it can upgrade
<img width="330" alt="image" src="https://user-images.githubusercontent.com/9952753/156815649-7699374a-ca31-4824-8aeb-a26fe089dd2f.png">

**Comment by lospringliu** [comment]
#13

**Comment by davay42** [comment]
Oh! I remember having such issues in firefox. It seems there are cases when the gun indexedDB store gets corrupt. I recall Mark talking about this bug being fixed in the latest GitHub version of Gun, but it has a new bug that prevents me from using it in the build.

@lospringliu The solution for the problem for me was to wipe the IndexedDB radata completely in the troublesome browser. It should be rather safe If you have another browser synced all the data.

**Comment by lospringliu** [comment]
you are right, after completely wipe off the data for the specific website, it gets back normal

So this is a false bug, thanks.
